org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.caching=false
kotlin.incremental=false

minecraft_version=1.20.1
forge_version=47.4.0
forge_dependency_version=47.4.0
mod_id=vs_electronic_warfare_fresh
mod_name=VS: Electronic Warfare Fresh
mod_version=0.3.0
mod_group_id=com.lauya.vselectronicwarfare
