modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "lauya"
description = '''
ComputerCraft radar peripheral for Valkyrien Skies ships with line-of-sight filtering.
'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge_dependency_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "computercraft"
mandatory = true
versionRange = "[1.113.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[2.3.0-beta.5,)"
ordering = "AFTER"
side = "BOTH"
